# Use root/example as user/password credentials
version: '3.1'

services:
  #https://hub.docker.com/_/mariadb
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: magento
    ports:
      - 3306:3306
    networks:
      frontend:
        ipv4_address: 172.18.0.200

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      frontend:
        ipv4_address: 172.18.0.202

  magneto:
    build: .
    restart: always
    ports:
      - 80:80
    volumes:
    - ./:/var/www/html/magento2
    networks:
      frontend:
        ipv4_address: 172.18.0.201

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.18.0.0/24